### ISSUE TITLE
Service offline

### ISSUE THREAD

**Issue by harry-wood** [dfacts/staticmaplite#16]
Currently http://staticmap.openstreetmap.de is **offline**. The website and (more importantly) all hosted static image URLs.

```
curl http://staticmap.openstreetmap.de
curl: (6) Could not resolve host: staticmap.openstreetmap.de
```
I'm not sure how long it has been broken like this, but [somebody reported](https://wiki.openstreetmap.org/wiki/User_talk:Harry_Wood#Simple_image_MediaWiki_Extension_broken.3F) all the wiki images (e.g. [pages like this](https://wiki.openstreetmap.org/wiki/London#OSM_Coverage)) have been broken for a few days.

**Comment by giggls** [comment]
We have been discussing this internally and decided against migrating staticmap to our new FOSSGIS server, because this service has been abused heavily in the past.

Unfortunately we did not know that it seems to have also been widely used in the OSM Wiki as well.

Given the massive abuse of the service in the past i would recommend a setup of the software directly on the OSM wiki server using a referer check.

We could do this as well, but I don't think, that "official" osm.org services should depend on projects we host on openstreetmap.de.

**Comment by giggls** [comment]
German Provider Strato terminated sponsoring of these old servers and I left it up to the Software authors to migrate their Servers to our new machine (payed for by FOSSGIS) or not.

I might have underestimated how much the service has been regularly used beside the abuse.

At the current state it is not possible to do some sort of phase out as the old servers are gone and re-enabling it would mean to migrate it fully to a new server. So no real need to phase it out again afterwards.

It is certainly possible to mitigate abuse e.g. using mod_bandwidth on a new install. If somebody wants to do this (@woodpeck @nakaner ?)  I would not object to even do it on our new server.

**Comment by Nakaner** [comment]
We at Geofabrik [forked](https://github.com/geofabrik/GfStaticmap) Staticmap long ago and have added lots of new features last year. Our fork contains all features of this repository except the wizard.

> Without seeing the traffic I can't be sure of the nature of the problem, but I guess "abusive" traffic was folks making interfaces which allow a user to pan around, moving the view to arbitrary coordinates, thus generating lots of cache miss requests. Then again abusive traffic might just mean very busy websites fetching cached images a lot. (Note: In either case I'm not aware of this being described as abuse anywhere. No request for developers not to do that, which would've been a good start to tackling the problem!)

I haven't seen the old logs either and only rely on what Frederik and Sven told me. Commercial users integrating the images in their services had been the main type of abuse. Their requests could be answered with the first level cache (cache of final images) but cause still a lot of traffic. We would have to look at the referrer to limit their usage of the service. Looking at IP addresses would be necessary to fight people using the service as a poor man's WMS.

We did not have a usage policy, that's something we will have to add.

**Comment by Marc-marc-marc** [comment]
to temporarily bypass the problem on the wiki, it is possible to use slippymap instead of map
it uses osm.org tiles instead of previous static images.
or maybe the template for map may be temporarily changed to use slippymap to avoid the need to edit too many page.

**Comment by Tigerfell** [comment]
@Marc-marc-marc not a very useful alternative given the issues of that (you may want to have a look at https://wiki.openstreetmap.org/wiki/Talk:Wiki#Bug:_map_appears_below_map_div_at_normal_desktop_window_sizes). Especially the limitation to have no more than one slippymap per page makes this useless in numerous cases. 
@Nakaner There seem to be  warning messages instead of images sometimes (like in the page linked in the first comment), so not fully usable yet.

**Comment by giggls** [comment]
@Tigerfell: Did you actually _read_ the warning message? You will need a referer.

**Comment by Tigerfell** [comment]
Ok, so you are basically saying that this issue is done in this repository, but there needs to be a change in the wiki extension?

**Comment by harry-wood** [comment]
Yeah tough usage limits, but nice one getting it running again! 

So is that on the new FOSSGIS server now?

**Comment by giggls** [comment]
@Tigerfell No. Usually clients will send a Referer and everything will be OK.
