### ISSUE TITLE
What is send a "referer" header ?

### ISSUE THREAD

**Issue by Filou07** [dfacts/staticmaplite#18]
I see this message 
staticmap.openstreetmap.de runs oin donated resources. Please use responsibly and send a "Referer" header. See github.com/dfacrs/staticmaplite if you want to run your own unlimited version

But nothing is mentioning how to send a referer

**Comment by Tigerfell** [comment]
Please have a look at #16

**Comment by harry-wood** [comment]
Yes so the _reason_ this new message is appearing, is that the service is working again (yay!) but with "tough usage limits". In particular, requiring referrer headers in the browser requests. Why? There is a concern around the nature of traffic hitting the server, and referer headers are needed for traceability e.g. The server admins can find out if a lot of traffic is caused by one very busy website, or one website using a design which creates a lot of cache misses. .... That's all described in a conversation on #16

But we could take it as separate issue, that "nothing is mentioning how to send a referer".   No advice for developers in general. I mean that could be added to the content on the staticmap website. ... or at least described here.

It's not really advice for end users. ... or is it? Well if you're behind a corporate firewall which strips all referrer headers, then maybe. Or maybe if you are browsing in incognito mode.

**Comment by Alwanw38ll** [comment]
May I ask you please to review/edit the Wiki details starting from this link : 
https://wiki.openstreetmap.org/wiki/Static_map_images
and 
https://wiki.openstreetmap.org/wiki/StaticMapLite
I think its necessary to bring the "http://staticmap.openstreetmap.de/" a live again.

**Comment by dfacts** [comment]
https://tools.ietf.org/html/rfc2616.html#section-14.36
